# Chapter 10 Sorting and Searching

from Gayle Laakmann McDowell's "Cracking the Coding Interview", 6th ed.

Ron Wu

## 10.1 merge sorted arrays A, B, and A has a large buffer

In [1]:
A = [1,5,8,10, None, None, None, None, None]
B = [3,7,10]

def mergeSorted(A, B):
    for i in reversed(range(len(A))):
        if A[i] != None:
            break
    
    EndPoint = i + len(B)
    j = len(B) - 1
    
    while j >= 0 and i >= 0:
        if A[i] > B[j]:
            A[EndPoint] = A[i]
            EndPoint -= 1
            i -= 1
        else: 
            A[EndPoint] = B[j]
            EndPoint -= 1
            j -= 1
    return A

mergeSorted(A, B)

[1, 3, 5, 7, 8, 10, 10, None, None]

## 10.2 sort strings by anagrams

In [2]:
def _CashString(s): 
    #assume contains only english letters
    result = [0]*26
    for l in s:
        result[ord(l.lower())-ord('a')] += 1 
    return result
        
def ModifiedQuickSort(A, B, left, right):
    index = _partition(A, B, left, right)
    if left < index - 1:
        ModifiedQuickSort(A,B, left, index - 1)
    if index < right: 
        ModifiedQuickSort(A,B, index, right)

def _partition(A,B, left, right):
    pivot = A[(left+right)/2]
    while left <= right:
        while A[left] < pivot:
            left += 1
        while A[right] > pivot:
            right -= 1
            
        if left <= right:
            A[left], A[right] = A[right], A[left]
            B[left], B[right] = B[right], B[left]
            left += 1
            right -= 1
            
    return left 

def sortStringAnagram(B):
    dicBysize = {}
    for b in B:
        if len(b) in dicBysize:
            dicBysize[len(b)].append(b)
        else:
            dicBysize[len(b)] = [b]
    
    result = []
    for (size, s) in dicBysize.iteritems():
        if len(s) == 1:
            result.extend(s)
        else:
            A = []
            for ss in s:
                A.append(_CashString(ss))
            ModifiedQuickSort(A, s,  0, len(A)-1)
            result.extend(s)
    return result

In [3]:
A = ['Rebuild', 'break', 'doc', 'baker', 'builder','Cod','US', 'tan','ant']
sortStringAnagram(A)

['US', 'Cod', 'doc', 'ant', 'tan', 'baker', 'break', 'builder', 'Rebuild']

## 10.3 search element in a sorted but rotated array

In [4]:
def binarySearch(A, n, left, right):
    if A[left] > n or A[right] < n or left > right:
        return None
    mid = (left + right) / 2
    if A[mid] == n:
        return mid
    if A[mid] > n:
        return binarySearch(A, n, left, mid - 1)
    else: 
        return binarySearch(A, n, mid + 1, right)

def _findRotation(A, left, right): 
    '''return the starting index of the original sorted array'''
    if left == right:
        return None
    if A[left] > A[left + 1]:
        return left
    if A[right] < A[right -1]:
        return right
    mid = (left + right) / 2 
    if A[mid] > A[mid+1] and A[mid] < A[mid-1]:
        return mid
    
    if A[left] > A[mid]:
        return _findRotation(A, left, mid)
    else:
        return _findRotation(A, mid, right)

def searchSortedRotated(A, n):
    indexUnrotated = _findRotation(A, 0, len(A) - 1)
    if indexUnrotated == 0 or None:
        return binarySearch(A, n, 0, len(A) - 1)
    
    a = binarySearch(A, n, 0, indexUnrotated - 1)
    b = binarySearch(A, n, indexUnrotated, len(A) - 1)
    
    if a != None:
        return a
    if b !=None:
        return b

In [5]:
n = 5
A = [15,16,19,20,25,1,3,4,5,7,10,14] 

searchSortedRotated(A,n)

8

## 10.4 like binary search with unknown right bound 

In [6]:
class Listy(object):
    def __init__(self, A):
        self.arr = A
        
    def elementAt(self, i):
        if i < len(self.arr) - 1 and i >=0 :
            return self.arr[i]
        else:
            return -1
        
def searchSortedList(lst, n, left, right):
    '''reverse binary search 1,2,4,8,16,...'''
    if right != None:
        return binarySearch(A, n, left, right)
    if lst.elementAt(left) > n:
        return None
    if lst.elementAt(left) == n:
        return left
    mid = left * 2 + 1
    if lst.elementAt(mid) == -1:
        return searchSortedList(lst, n, left + 1, None)
    if lst.elementAt(mid) == n:
        return mid
    if lst.elementAt(mid) < n:
        return searchSortedList(lst, n, mid, None)
    if lst.elementAt(mid) > n:
        return binarySearch(A, n, left, right)

In [7]:
A = [1,3,5,7,13,26,45,67]
iList = Listy(A)
print zip(A,[x for x in range(len(A))])
n = 13
print 'the index of', n , 'is',searchSortedList(iList, n, 0 , None)

[(1, 0), (3, 1), (5, 2), (7, 3), (13, 4), (26, 5), (45, 6), (67, 7)]
the index of 13 is 4


## 10.5 sort a sparse array of strings

In [8]:
def findIndexSparseArray(A, find):
    index = 0
    for a in A:
        if len(a)!=0:
            if a == find:
                return index
        index += 1
    return None

In [9]:
A = ['at','','','','ball','','','car','','','dad','','']
find = 'ball'
findIndexSparseArray(A, find)

4

## 10.6 sort each line of strings of a 20GB file

In [10]:
#typical memory is ~1GB
#so divide 20GB into 20 files and sort each file
#then merge sorted files
#take two sorted files, take .5GB of each, begin merge, when the result gets full,
#write it to the disk, and continue till merge finishes

## 10.7 find missing integer in the range of 4 billion integers

In [11]:
#the memory is only 10MB ~ 2^22, recall 2^20 bits ~ 1MB
# so if we created a boolean vectors 0 or 1 to represent all
#4 billion ( ~ 2^30) distinct integers we will need (2^32) ~ 1 Gigabyte of memory

#we cannot dump everything in the memory, so we will create 2^10 ~ 1000 different files 
#to store the boolean vectors. As we go through the integers, we write to the appropriate file 


## 10.8 find duplicates

In [12]:
# 4 kilobytes of memory ~ 8 * 4 * 2^10 ~ 32000, so just enough to store the boolean vectors 
# in the memory
number = [1,2,3,3,5,6,7,8,8,9,10,11]

found = [False]*32000
for n in number:
    if found[n] == 1:
        print 'duplicate found', n 
    else:
        found[n] = 1
    

duplicate found 3
duplicate found 8


## 10.9 search a sorted matrix

In [13]:
def binarySearch(A, n, left, right):
    if A[left] > n or A[right] < n or left > right:
        return None
    mid = (left + right) / 2
    if A[mid] == n:
        return mid
    if A[mid] > n:
        return binarySearch(A, n, left, mid - 1)
    else: 
        return binarySearch(A, n, mid + 1, right)
    
def modifiedBinarySearch(A, n, left, right):
    '''if the item is not found, return its left, right indices boundary'''
    
    if A[left] > n:
        return [None, left]
    if A[right] < n:
        return [right, None]
    
    if A[left] == n:
        return [left, left]
    if A[right] == n:
        return [right, right]
    
    if left == right - 1:
        return [left, right]
    
    mid = (left + right) / 2
    if A[mid] == n:
        return [mid, mid]
                
    if A[mid] > n:  
        return modifiedBinarySearch(A, n, left, mid)
    else:  
        return modifiedBinarySearch(A, n, mid, right)

def searchSorted(Mat, n , r, c):
    M = len(Mat)
    N = len(Mat[0]) 
    
    if r == M - 1:
        f = binarySearch(Mat[r], n, 0, c)
        if f == None:
            return [f,f]
        else:
            return [r,f]
        
    [a, b] = modifiedBinarySearch(Mat[r], n, 0, c) 
    if a == None: 
        return [None, None]
    if b == None:  
        return searchSorted(Mat, n , r + 1, c)
    
    if a == b:
        return [r,a]
    
    return searchSorted(Mat, n , r + 1, a)
    
    

In [14]:
Mat = [[1,3,6],[2,5,7], [4,6,9]]
n = 5 
import numpy as np
print np.matrix(Mat)
print 'search for',n,'found? at',searchSorted(Mat, n, 0, len(Mat[0])-1)

[[1 3 6]
 [2 5 7]
 [4 6 9]]
search for 5 found? at [1, 1]


## 10.10 rank of stream

In [15]:
class myStream(object):
    def __init__(self):
        self.arr = []
        self.ranking = {}
    def track(self, n): 
        if n in self.ranking:
            for k in self.ranking:
                if k >= n:
                    self.ranking[k] += 1
        else: 
            self.ranking[n] = 0
            for k in self.ranking:
                if k > n:
                    self.ranking[k] += 1
                elif k < n:
                    self.ranking[n] = max(self.ranking[k]+1, self.ranking[n]) 
        self.arr.append(n)
    
    def getRank(self, n):
        if n in self.ranking:
            return self.ranking[n]
        return None

In [16]:
A = [5,1,4,4,5,9,7,13,3]
n = 3
iStream = myStream()
for a in A:
    iStream.track(a)

print 'the rank of',n,'is',iStream.getRank(n)
print 'the entire rankings are', iStream.ranking

the rank of 3 is 1
the entire rankings are {1: 0, 3: 1, 4: 3, 5: 5, 7: 6, 9: 7, 13: 8}


## 10.11 peaks and valleys

In [17]:
def quickSort(A, left, right):
    index = partition(A, left, right)  
    if left < index - 1:
        quickSort(A,left, index - 1)
    if index < right: 
        quickSort(A, index, right)

def partition(A,left, right):
    pivot = A[(left + right) / 2]
    while left <= right:
        while A[left] < pivot:
            left += 1
        while A[right] > pivot:
            right -= 1
            
        if left <= right:
            A[left], A[right] = A[right], A[left] 
            left += 1
            right -= 1
            
    return left 

def peakValleyAlternate(A):
    quickSort(A, 0, len(A) - 1)  
    result = []
    left = 0
    right = len(A) - 1 
    while left < right:
        result.append(A[right])
        result.append(A[left])
        left += 1
        right -= 1 
    if len(A) % 2 ==1:
        result.append(A[right])
    return result

In [18]:
A = [5,3,1,2,3]
peakValleyAlternate(A)

[5, 1, 3, 2, 3]